# Generated by Django 3.1.7 on 2021-02-24 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('class_no', models.CharField(max_length=2)),
                ('parent_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['created'],
            },
        ),
    ]
