# Generated by Django 3.1.7 on 2021-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='2021', max_length=4),
        ),
    ]
